services:
  - type: web
    name: vpn-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    branch: main
    plan: free
    autoDeploy: true

  - type: web
    name: vpn-server
    env: docker
    dockerfilePath: /vpn/Dockerfile
    branch: main
    plan: free
    autoDeploy: true
